name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.12.0
publish_to: none
homepage: https://github.com/tobrun/flutter-mapbox-gl

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/revoltgames/neopolis_mapbox.git
      path: mapbox_gl_platform_interface
      ref: v0.11.9

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web
